[tool.black]
skip-string-normalization = true
exclude = '''
/(
    _extra
  | \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
verbose = true
